/**
 * Local visual fixture for Finance screenshots.
 * Never used when Finance remote READ is on. Not a Production ledger.
 */
import type { Transaction } from "@/lib/commerce/domain";
import type { Expense } from "./domain";

export const FINANCE_VISUAL_FIXTURE_ONLY = true;

export function financeVisualFixtureTransactions(): Transaction[] {
  return [
    {
      id: "tx-fx-sale",
      organizationId: "org-the-enjoye",
      locationId: "loc-enjoye-main",
      customerId: "cust-fx-1",
      transactionNumber: "TX-20261006-0002",
      status: "COMPLETED",
      items: [
        {
          id: "i-sale",
          type: "PACKAGE_PURCHASE",
          nameSnapshot: "性感美胸10堂",
          unitPrice: 22000,
          quantity: 1,
          lineSubtotal: 22000,
          discountAmount: 0,
          lineTotal: 22000,
          sessionCountSnapshot: 10,
        },
      ],
      discounts: [],
      payments: [
        { id: "p-sale", method: "CASH", amount: 22000, paidAt: "2026-10-06T08:32:00.000Z" },
      ],
      subtotal: 22000,
      discountTotal: 0,
      total: 22000,
      currency: "TWD",
      createdByStaffId: "staff-001",
      completedAt: "2026-10-06T08:32:00.000Z",
    },
    {
      id: "tx-fx-cash",
      organizationId: "org-the-enjoye",
      locationId: "loc-enjoye-main",
      customerId: "cust-fx-2",
      transactionNumber: "TX-20261006-0004",
      status: "COMPLETED",
      items: [
        {
          id: "i-cash",
          type: "SERVICE",
          nameSnapshot: "美波澎潤upupSPA",
          unitPrice: 1800,
          quantity: 1,
          lineSubtotal: 1800,
          discountAmount: 0,
          lineTotal: 1800,
        },
      ],
      discounts: [],
      payments: [
        { id: "p-cash", method: "CASH", amount: 1800, paidAt: "2026-10-06T09:12:00.000Z" },
      ],
      subtotal: 1800,
      discountTotal: 0,
      total: 1800,
      currency: "TWD",
      createdByStaffId: "staff-001",
      completedAt: "2026-10-06T09:12:00.000Z",
    },
    {
      id: "tx-fx-redeem",
      organizationId: "org-the-enjoye",
      locationId: "loc-enjoye-main",
      customerId: "cust-fx-1",
      transactionNumber: "TX-20261006-0006",
      status: "COMPLETED",
      items: [
        {
          id: "i-redeem",
          type: "SERVICE",
          nameSnapshot: "美波澎潤upupSPA",
          unitPrice: 1800,
          quantity: 1,
          lineSubtotal: 1800,
          discountAmount: 1800,
          lineTotal: 0,
        },
      ],
      discounts: [],
      payments: [],
      packageRedemption: {
        customerPackageId: "cpkg-fx-1",
        serviceId: "svc-1",
        sessions: 1,
      },
      subtotal: 1800,
      discountTotal: 1800,
      total: 0,
      currency: "TWD",
      createdByStaffId: "staff-001",
      completedAt: "2026-10-06T09:19:00.000Z",
    },
  ];
}

export function financeVisualFixtureExpenses(): Expense[] {
  return [
    {
      id: "exp-fx-1",
      appId: "exp-fx-1",
      organizationId: "org-the-enjoye",
      locationId: "loc-enjoye-main",
      expenseDate: "2026-10-06",
      category: "SUPPLIES",
      name: "美胸按摩霜",
      amountMinor: 3000,
      paymentMethod: "CASH",
      vendor: "XX美容材料",
      note: "",
      receiptUrl: null,
      createdByStaffId: "staff-001",
      createdAt: "2026-10-06T01:00:00.000Z",
      updatedAt: "2026-10-06T01:00:00.000Z",
    },
    {
      id: "exp-fx-2",
      appId: "exp-fx-2",
      organizationId: "org-the-enjoye",
      locationId: "loc-enjoye-main",
      expenseDate: "2026-10-05",
      category: "MARKETING",
      name: "IG廣告",
      amountMinor: 8000,
      paymentMethod: "TRANSFER",
      vendor: "Meta",
      note: "",
      receiptUrl: null,
      createdByStaffId: "staff-001",
      createdAt: "2026-10-05T01:00:00.000Z",
      updatedAt: "2026-10-05T01:00:00.000Z",
    },
    {
      id: "exp-fx-3",
      appId: "exp-fx-3",
      organizationId: "org-the-enjoye",
      locationId: "loc-enjoye-main",
      expenseDate: "2026-10-02",
      category: "RENT",
      name: "10月份房租",
      amountMinor: 23000,
      paymentMethod: "TRANSFER",
      vendor: "房東",
      note: "",
      receiptUrl: null,
      createdByStaffId: "staff-001",
      createdAt: "2026-10-02T01:00:00.000Z",
      updatedAt: "2026-10-02T01:00:00.000Z",
    },
    {
      id: "exp-fx-4",
      appId: "exp-fx-4",
      organizationId: "org-the-enjoye",
      locationId: "loc-enjoye-main",
      expenseDate: "2026-10-01",
      category: "SALARY",
      name: "10月薪資",
      amountMinor: 42000,
      paymentMethod: "TRANSFER",
      vendor: "",
      note: "",
      receiptUrl: null,
      createdByStaffId: "staff-001",
      createdAt: "2026-10-01T01:00:00.000Z",
      updatedAt: "2026-10-01T01:00:00.000Z",
    },
    {
      id: "exp-fx-5",
      appId: "exp-fx-5",
      organizationId: "org-the-enjoye",
      locationId: "loc-enjoye-main",
      expenseDate: "2026-10-03",
      category: "UTILITIES",
      name: "水電",
      amountMinor: 5000,
      paymentMethod: "TRANSFER",
      vendor: "",
      note: "",
      receiptUrl: null,
      createdByStaffId: "staff-001",
      createdAt: "2026-10-03T01:00:00.000Z",
      updatedAt: "2026-10-03T01:00:00.000Z",
    },
    {
      id: "exp-fx-6",
      appId: "exp-fx-6",
      organizationId: "org-the-enjoye",
      locationId: "loc-enjoye-main",
      expenseDate: "2026-10-04",
      category: "OTHER",
      name: "雜支",
      amountMinor: 3000,
      paymentMethod: "CASH",
      vendor: "",
      note: "",
      receiptUrl: null,
      createdByStaffId: "staff-001",
      createdAt: "2026-10-04T01:00:00.000Z",
      updatedAt: "2026-10-04T01:00:00.000Z",
    },
  ];
}
